package com.scalint.reporter

import com.scalint.core._
import com.scalint.rules.RuleRegistry
import java.io.{File, PrintWriter}
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

/**
 * HTML Report Generator
 *
 * Generates interactive HTML reports with:
 * - Summary dashboard with charts
 * - Issue breakdown by category, severity, and file
 * - Code snippets with syntax highlighting
 * - Filtering and search functionality
 * - Export options
 */
object HtmlReporter {

  /**
   * Generate HTML report from analysis result
   */
  def generateReport(
    result: AnalysisResult,
    outputPath: String = "scalint-report.html",
    projectName: String = "Project",
    includeCodeSnippets: Boolean = true
  ): Boolean = {
    try {
      val html = buildHtml(result, projectName, includeCodeSnippets)
      val writer = new PrintWriter(new File(outputPath))
      try {
        writer.write(html)
        true
      } finally {
        writer.close()
      }
    } catch {
      case _: Exception => false
    }
  }

  private def buildHtml(
    result: AnalysisResult,
    projectName: String,
    includeCodeSnippets: Boolean
  ): String = {
    val timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))
    val issuesByCategory = result.allIssues.groupBy(_.category)
    val issuesBySeverity = result.allIssues.groupBy(_.severity)
    val issuesByFile = result.allIssues.groupBy(_.position.file)

    s"""<!DOCTYPE html>
       |<html lang="en">
       |<head>
       |  <meta charset="UTF-8">
       |  <meta name="viewport" content="width=device-width, initial-scale=1.0">
       |  <title>ScalaLint Report - $projectName</title>
       |  <style>
       |    ${generateCss()}
       |  </style>
       |</head>
       |<body>
       |  <header>
       |    <h1>🔍 ScalaLint Report</h1>
       |    <div class="meta">
       |      <span class="project">$projectName</span>
       |      <span class="timestamp">Generated: $timestamp</span>
       |    </div>
       |  </header>
       |
       |  <main>
       |    ${generateSummarySection(result)}
       |    ${generateChartsSection(issuesByCategory, issuesBySeverity)}
       |    ${generateFiltersSection()}
       |    ${generateIssuesSection(result, issuesByFile, includeCodeSnippets)}
       |  </main>
       |
       |  <footer>
       |    <p>Generated by <a href="https://github.com/your-repo/scalint">ScalaLint</a></p>
       |    <p>Total rules available: ${RuleRegistry.ruleCount}</p>
       |  </footer>
       |
       |  <script>
       |    ${generateJavaScript()}
       |  </script>
       |</body>
       |</html>""".stripMargin
  }

  private def generateCss(): String = {
    """
      |:root {
      |  --error-color: #dc3545;
      |  --warning-color: #ffc107;
      |  --info-color: #17a2b8;
      |  --hint-color: #6c757d;
      |  --bg-color: #f8f9fa;
      |  --card-bg: #ffffff;
      |  --text-color: #212529;
      |  --border-color: #dee2e6;
      |}
      |
      |* { box-sizing: border-box; margin: 0; padding: 0; }
      |
      |body {
      |  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      |  background: var(--bg-color);
      |  color: var(--text-color);
      |  line-height: 1.6;
      |}
      |
      |header {
      |  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      |  color: white;
      |  padding: 2rem;
      |  text-align: center;
      |}
      |
      |header h1 { font-size: 2rem; margin-bottom: 0.5rem; }
      |header .meta { opacity: 0.9; font-size: 0.9rem; }
      |header .project { font-weight: bold; margin-right: 1rem; }
      |
      |main { max-width: 1400px; margin: 0 auto; padding: 2rem; }
      |
      |.summary {
      |  display: grid;
      |  grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
      |  gap: 1rem;
      |  margin-bottom: 2rem;
      |}
      |
      |.stat-card {
      |  background: var(--card-bg);
      |  padding: 1.5rem;
      |  border-radius: 8px;
      |  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
      |  text-align: center;
      |}
      |
      |.stat-card .value {
      |  font-size: 2.5rem;
      |  font-weight: bold;
      |  margin-bottom: 0.5rem;
      |}
      |
      |.stat-card .label { color: #666; font-size: 0.9rem; }
      |
      |.stat-card.error .value { color: var(--error-color); }
      |.stat-card.warning .value { color: var(--warning-color); }
      |.stat-card.info .value { color: var(--info-color); }
      |.stat-card.hint .value { color: var(--hint-color); }
      |
      |.charts {
      |  display: grid;
      |  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
      |  gap: 1rem;
      |  margin-bottom: 2rem;
      |}
      |
      |.chart-card {
      |  background: var(--card-bg);
      |  padding: 1.5rem;
      |  border-radius: 8px;
      |  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
      |}
      |
      |.chart-card h3 { margin-bottom: 1rem; color: #333; }
      |
      |.bar-chart .bar-item {
      |  display: flex;
      |  align-items: center;
      |  margin-bottom: 0.5rem;
      |}
      |
      |.bar-chart .bar-label {
      |  width: 100px;
      |  font-size: 0.85rem;
      |  color: #666;
      |}
      |
      |.bar-chart .bar-fill {
      |  flex: 1;
      |  height: 20px;
      |  background: #e9ecef;
      |  border-radius: 4px;
      |  overflow: hidden;
      |}
      |
      |.bar-chart .bar-fill-inner {
      |  height: 100%;
      |  border-radius: 4px;
      |  transition: width 0.3s ease;
      |}
      |
      |.bar-chart .bar-value {
      |  width: 50px;
      |  text-align: right;
      |  font-size: 0.85rem;
      |  font-weight: bold;
      |}
      |
      |.filters {
      |  background: var(--card-bg);
      |  padding: 1rem;
      |  border-radius: 8px;
      |  margin-bottom: 2rem;
      |  display: flex;
      |  gap: 1rem;
      |  flex-wrap: wrap;
      |  align-items: center;
      |}
      |
      |.filters input, .filters select {
      |  padding: 0.5rem;
      |  border: 1px solid var(--border-color);
      |  border-radius: 4px;
      |  font-size: 0.9rem;
      |}
      |
      |.filters input[type="text"] { flex: 1; min-width: 200px; }
      |
      |.issues-list { margin-bottom: 2rem; }
      |
      |.file-group {
      |  background: var(--card-bg);
      |  border-radius: 8px;
      |  margin-bottom: 1rem;
      |  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
      |  overflow: hidden;
      |}
      |
      |.file-header {
      |  padding: 1rem;
      |  background: #f1f3f5;
      |  border-bottom: 1px solid var(--border-color);
      |  cursor: pointer;
      |  display: flex;
      |  justify-content: space-between;
      |  align-items: center;
      |}
      |
      |.file-header:hover { background: #e9ecef; }
      |
      |.file-name { font-family: monospace; font-weight: bold; }
      |.file-count { background: #667eea; color: white; padding: 0.2rem 0.6rem; border-radius: 12px; font-size: 0.8rem; }
      |
      |.file-issues { display: none; }
      |.file-group.expanded .file-issues { display: block; }
      |
      |.issue {
      |  padding: 1rem;
      |  border-bottom: 1px solid var(--border-color);
      |}
      |
      |.issue:last-child { border-bottom: none; }
      |
      |.issue-header {
      |  display: flex;
      |  align-items: center;
      |  gap: 0.5rem;
      |  margin-bottom: 0.5rem;
      |}
      |
      |.severity-badge {
      |  padding: 0.2rem 0.5rem;
      |  border-radius: 4px;
      |  font-size: 0.75rem;
      |  font-weight: bold;
      |  text-transform: uppercase;
      |}
      |
      |.severity-error { background: var(--error-color); color: white; }
      |.severity-warning { background: var(--warning-color); color: #000; }
      |.severity-info { background: var(--info-color); color: white; }
      |.severity-hint { background: var(--hint-color); color: white; }
      |
      |.rule-id { font-family: monospace; color: #666; font-size: 0.85rem; }
      |.line-number { color: #999; font-size: 0.85rem; }
      |
      |.issue-message { margin-bottom: 0.5rem; }
      |
      |.issue-suggestion {
      |  background: #e8f5e9;
      |  padding: 0.5rem;
      |  border-radius: 4px;
      |  font-size: 0.85rem;
      |  color: #2e7d32;
      |  margin-top: 0.5rem;
      |}
      |
      |.code-snippet {
      |  background: #282c34;
      |  color: #abb2bf;
      |  padding: 1rem;
      |  border-radius: 4px;
      |  font-family: 'Fira Code', monospace;
      |  font-size: 0.85rem;
      |  overflow-x: auto;
      |  margin-top: 0.5rem;
      |}
      |
      |footer {
      |  text-align: center;
      |  padding: 2rem;
      |  color: #666;
      |  font-size: 0.9rem;
      |}
      |
      |footer a { color: #667eea; }
      |
      |@media (max-width: 768px) {
      |  .summary { grid-template-columns: repeat(2, 1fr); }
      |  .filters { flex-direction: column; }
      |  .filters input[type="text"] { width: 100%; }
      |}
      |""".stripMargin
  }

  private def generateSummarySection(result: AnalysisResult): String = {
    s"""<section class="summary">
       |  <div class="stat-card">
       |    <div class="value">${result.totalIssueCount}</div>
       |    <div class="label">Total Issues</div>
       |  </div>
       |  <div class="stat-card error">
       |    <div class="value">${result.errorCount}</div>
       |    <div class="label">Errors</div>
       |  </div>
       |  <div class="stat-card warning">
       |    <div class="value">${result.warningCount}</div>
       |    <div class="label">Warnings</div>
       |  </div>
       |  <div class="stat-card info">
       |    <div class="value">${result.infoCount}</div>
       |    <div class="label">Info</div>
       |  </div>
       |  <div class="stat-card hint">
       |    <div class="value">${result.hintCount}</div>
       |    <div class="label">Hints</div>
       |  </div>
       |  <div class="stat-card">
       |    <div class="value">${result.analyzedFiles}</div>
       |    <div class="label">Files Analyzed</div>
       |  </div>
       |</section>""".stripMargin
  }

  private def generateChartsSection(
    issuesByCategory: Map[Category, Seq[LintIssue]],
    issuesBySeverity: Map[Severity, Seq[LintIssue]]
  ): String = {
    val totalIssues = issuesByCategory.values.flatten.size.max(1)

    val categoryBars = issuesByCategory.toSeq.sortBy(-_._2.size).take(8).map { case (cat, issues) =>
      val percentage = (issues.size * 100) / totalIssues
      val color = getCategoryColor(cat)
      s"""<div class="bar-item">
         |  <span class="bar-label">${cat.name}</span>
         |  <div class="bar-fill">
         |    <div class="bar-fill-inner" style="width: ${percentage}%; background: $color;"></div>
         |  </div>
         |  <span class="bar-value">${issues.size}</span>
         |</div>""".stripMargin
    }.mkString("\n")

    val severityBars = Seq(Severity.Error, Severity.Warning, Severity.Info, Severity.Hint).map { sev =>
      val count = issuesBySeverity.getOrElse(sev, Seq.empty).size
      val percentage = (count * 100) / totalIssues.max(1)
      val color = getSeverityColor(sev)
      s"""<div class="bar-item">
         |  <span class="bar-label">${sev.name}</span>
         |  <div class="bar-fill">
         |    <div class="bar-fill-inner" style="width: ${percentage}%; background: $color;"></div>
         |  </div>
         |  <span class="bar-value">$count</span>
         |</div>""".stripMargin
    }.mkString("\n")

    s"""<section class="charts">
       |  <div class="chart-card">
       |    <h3>Issues by Category</h3>
       |    <div class="bar-chart">
       |      $categoryBars
       |    </div>
       |  </div>
       |  <div class="chart-card">
       |    <h3>Issues by Severity</h3>
       |    <div class="bar-chart">
       |      $severityBars
       |    </div>
       |  </div>
       |</section>""".stripMargin
  }

  private def generateFiltersSection(): String = {
    s"""<section class="filters">
       |  <input type="text" id="searchInput" placeholder="Search issues..." onkeyup="filterIssues()">
       |  <select id="severityFilter" onchange="filterIssues()">
       |    <option value="">All Severities</option>
       |    <option value="error">Error</option>
       |    <option value="warning">Warning</option>
       |    <option value="info">Info</option>
       |    <option value="hint">Hint</option>
       |  </select>
       |  <select id="categoryFilter" onchange="filterIssues()">
       |    <option value="">All Categories</option>
       |    ${Category.all.map(c => s"""<option value="${c.name}">${c.name}</option>""").mkString("\n    ")}
       |  </select>
       |  <button onclick="expandAll()">Expand All</button>
       |  <button onclick="collapseAll()">Collapse All</button>
       |</section>""".stripMargin
  }

  private def generateIssuesSection(
    result: AnalysisResult,
    issuesByFile: Map[String, Seq[LintIssue]],
    includeCodeSnippets: Boolean
  ): String = {
    val fileGroups = issuesByFile.toSeq.sortBy(-_._2.size).map { case (file, issues) =>
      val issueItems = issues.sortBy(i => (i.severity.level * -1, i.position.startLine)).map { issue =>
        val severityClass = s"severity-${issue.severity.name}"
        val suggestion = issue.suggestion.map(s => s"""<div class="issue-suggestion">💡 $s</div>""").getOrElse("")
        val snippet = issue.codeSnippet.filter(_ => includeCodeSnippets).map(s =>
          s"""<pre class="code-snippet">${escapeHtml(s)}</pre>"""
        ).getOrElse("")

        s"""<div class="issue" data-severity="${issue.severity.name}" data-category="${issue.category.name}" data-rule="${issue.ruleId}">
           |  <div class="issue-header">
           |    <span class="severity-badge $severityClass">${issue.severity.name}</span>
           |    <span class="rule-id">${issue.ruleId}</span>
           |    <span class="line-number">Line ${issue.position.startLine}</span>
           |  </div>
           |  <div class="issue-message">${escapeHtml(issue.message)}</div>
           |  $suggestion
           |  $snippet
           |</div>""".stripMargin
      }.mkString("\n")

      val shortFile = file.split("/").takeRight(3).mkString("/")

      s"""<div class="file-group">
         |  <div class="file-header" onclick="toggleFileGroup(this.parentElement)">
         |    <span class="file-name">$shortFile</span>
         |    <span class="file-count">${issues.size}</span>
         |  </div>
         |  <div class="file-issues">
         |    $issueItems
         |  </div>
         |</div>""".stripMargin
    }.mkString("\n")

    s"""<section class="issues-list">
       |  <h2>Issues by File</h2>
       |  $fileGroups
       |</section>""".stripMargin
  }

  private def generateJavaScript(): String = {
    """
      |function toggleFileGroup(element) {
      |  element.classList.toggle('expanded');
      |}
      |
      |function expandAll() {
      |  document.querySelectorAll('.file-group').forEach(el => el.classList.add('expanded'));
      |}
      |
      |function collapseAll() {
      |  document.querySelectorAll('.file-group').forEach(el => el.classList.remove('expanded'));
      |}
      |
      |function filterIssues() {
      |  const search = document.getElementById('searchInput').value.toLowerCase();
      |  const severity = document.getElementById('severityFilter').value;
      |  const category = document.getElementById('categoryFilter').value;
      |
      |  document.querySelectorAll('.issue').forEach(issue => {
      |    const text = issue.textContent.toLowerCase();
      |    const issueSeverity = issue.dataset.severity;
      |    const issueCategory = issue.dataset.category;
      |
      |    const matchesSearch = !search || text.includes(search);
      |    const matchesSeverity = !severity || issueSeverity === severity;
      |    const matchesCategory = !category || issueCategory === category;
      |
      |    issue.style.display = matchesSearch && matchesSeverity && matchesCategory ? 'block' : 'none';
      |  });
      |
      |  // Update file group visibility
      |  document.querySelectorAll('.file-group').forEach(group => {
      |    const visibleIssues = group.querySelectorAll('.issue[style="display: block"], .issue:not([style])');
      |    const hiddenIssues = group.querySelectorAll('.issue[style="display: none"]');
      |    group.style.display = visibleIssues.length > 0 || hiddenIssues.length === 0 ? 'block' : 'none';
      |  });
      |}
      |""".stripMargin
  }

  private def getCategoryColor(category: Category): String = category match {
    case Category.Bug => "#dc3545"
    case Category.Security => "#9c27b0"
    case Category.Performance => "#ff9800"
    case Category.Spark => "#e65100"
    case Category.DeltaLake => "#0d47a1"
    case Category.Concurrency => "#673ab7"
    case Category.FunctionalStyle => "#4caf50"
    case Category.Style => "#607d8b"
    case _ => "#667eea"
  }

  private def getSeverityColor(severity: Severity): String = severity match {
    case Severity.Error => "#dc3545"
    case Severity.Warning => "#ffc107"
    case Severity.Info => "#17a2b8"
    case Severity.Hint => "#6c757d"
  }

  private def escapeHtml(s: String): String = {
    s.replace("&", "&amp;")
      .replace("<", "&lt;")
      .replace(">", "&gt;")
      .replace("\"", "&quot;")
      .replace("'", "&#39;")
  }
}
